### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by SiyuanHuang1** [bsungwoo/STopover#8]
First of all, I would like to express my sincere gratitude for your efforts in developing the series of single cell and spatial transcriptomics analysis tools. Your work is greatly appreciated.

Recently, I attempted to download and install STopover. However, I encountered an error that has persisted across multiple attempts. Notably, I don't believe the issue is related to my network connection, as I was able to successfully download Jupyter. Furthermore, I have tried downloading STopover on four different devices, but unfortunately, I encountered the same error on each one.

I am including the specific error report below for your reference. Could you kindly assist me in resolving this issue? Any guidance or suggestions you can provide would be immensely helpful.

![](https://github.com/bsungwoo/STopover/assets/37017211/8fc45564-f4a3-4159-a001-988eda5becf2)

Thank you in advance for your time and assistance. I am looking forward to your response and am eager to use STopover for my research.

**Comment by bsungwoo** [comment]
@SiyuanHuang1, thank you for your interest in the STopover model. I installed the STopover package using the above command, and I successfully installed STopover. I am not sure about the cause of the GitHub connection error and am attempting to reproduce it, but I have been unsuccessful so far. Could you check if the below command to install "celltypist" works well?
```Plain Text
pip install git+https://github.com/Teichlab/celltypist
```
If the above installation results in the same error as STopover, it can be solved by following 1 and 2.
1. Could you please check the firewall settings of your network before installing via the "pip install git+" command?
2. Please see the following Stackoverflow questions and answers: https://stackoverflow.com/questions/18356502/github-failed-to-connect-to-github-443-windows-failed-to-connect-to-github.

**Comment by bsungwoo** [comment]
@SiyuanHuang1, if you cannot solve the problem using the above 1, 2 approaches, could you first download (or git clone) the repository to your local, move to the directory where "setup.py" is located, and install the package by typing the following command? Python version must be 3.9 when installing with the following command.
```Plain Text
conda create -n STopover python=3.9
conda activate STopover
python setup.py install
```

**Comment by SiyuanHuang1** [comment]
Thank you so much for your response! Just as you pointed out, I encountered the same error after executing `pip install git+https://github.com/Teichlab/celltypist`, so it should be the firewall issue you mentioned. For simplicity, I chose the Plan B you suggested. I have now successfully installed STopover and have successfully processed the visium data.
